apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    pod: mongo-server
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Pod
metadata:
  name: mongo-server-pod
  labels:
    pod: mongo-server
spec:
  containers:
  - name: mongo-server-container
    image: mongo:4.2.0
