apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: mongo-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: gengo.com/v1
    resource: mongomigrations
  childResources:
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: Recreate
  - apiVersion: v1
    resource: pods
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://migration-service.webhook/sync
