apply-crd:
	kubectl apply -f crd.yaml
	kubectl get crd

apply-controller:
	kubectl apply -f controller.yaml
	kubectl get compositecontroller

get-mongo-migration:
	kubectl get MongoMigration

describe-mongo-migration:
	kubectl describe MongoMigration mongo-migration

delete-crd:
	kubectl delete -f crd.yaml

delete-controller:
	kubectl delete -f controller.yaml
